### ISSUE TITLE
Stealing your code

### ISSUE THREAD

**Issue by stevie-mayhew** [axllent/silverstripe-seo-editor#1]
Hey Ralph!

Some of the stuff you've done here looks like it would be great in the base module as well. Any chance we can steal it? 😄 

Cheers,
Stevie

**Comment by axllent** [comment]
Hiya Stevie,

As you're aware this module is initially based on yours (as you probably saw the credit in the README), though I took it in a somewhat different direction to better suit our requirements, plus added a few "fail safes" and features that I found fitting. It quickly became too distant for a functional git fork (merge requests would have probably resulted in large rewrites to your code and change in functionality), hence it now being a stand-alone project.

But of course, not a problem at all to "inherit" some stuff, though I'd also appreciate some credit too ;-)

Cheers,
Ralph
